//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace Storm.Generated
{
	
	
	public class Generated_ViewHolder_31 : Storm.Mvvm.BaseViewHolder
	{
		
		private TextView _generated_field_813;
		
		private ILocalizationService _generated_field_814;
		
		protected TextView Generated_ViewElement_287
		{
			get
			{
				if ((this._generated_field_813 == null))
				{
					this._generated_field_813 = this.View.FindViewById<TextView>(Resource.Id.Generated_ViewElement_287);
				}
				return this._generated_field_813;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_814 == null))
				{
					this._generated_field_814 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_814;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_595 = new BindingObject(this.Generated_ViewElement_287);
			result.Add(generated_bindingObject_595);
			BindingExpression generated_bindingExpression_657 = new BindingExpression("Text", "Name");
			generated_bindingObject_595.AddExpression(generated_bindingExpression_657);
			return result;
		}
	}
}
