//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace Storm.Generated
{
	
	
	public class Generated_ViewHolder_2 : Storm.Mvvm.BaseViewHolder
	{
		
		private TextView _generated_field_26;
		
		private TextView _generated_field_27;
		
		private ILocalizationService _generated_field_28;
		
		protected TextView Generated_ViewElement_7
		{
			get
			{
				if ((this._generated_field_26 == null))
				{
					this._generated_field_26 = this.View.FindViewById<TextView>(Resource.Id.Generated_ViewElement_7);
				}
				return this._generated_field_26;
			}
		}
		
		protected TextView Generated_ViewElement_8
		{
			get
			{
				if ((this._generated_field_27 == null))
				{
					this._generated_field_27 = this.View.FindViewById<TextView>(Resource.Id.Generated_ViewElement_8);
				}
				return this._generated_field_27;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_28 == null))
				{
					this._generated_field_28 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_28;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_14 = new BindingObject(this.Generated_ViewElement_7);
			result.Add(generated_bindingObject_14);
			BindingExpression generated_bindingExpression_14 = new BindingExpression("Text", "Name");
			generated_bindingObject_14.AddExpression(generated_bindingExpression_14);
			BindingObject generated_bindingObject_15 = new BindingObject(this.Generated_ViewElement_8);
			result.Add(generated_bindingObject_15);
			BindingExpression generated_bindingExpression_15 = new BindingExpression("Text", "Description");
			generated_bindingObject_15.AddExpression(generated_bindingExpression_15);
			return result;
		}
	}
}
