//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace Storm.Generated
{
	
	
	public class Generated_ViewHolder_3 : Storm.Mvvm.BaseViewHolder
	{
		
		private TextView _generated_field_39;
		
		private TextView _generated_field_40;
		
		private ILocalizationService _generated_field_41;
		
		protected TextView Generated_ViewElement_10
		{
			get
			{
				if ((this._generated_field_39 == null))
				{
					this._generated_field_39 = this.View.FindViewById<TextView>(Resource.Id.Generated_ViewElement_10);
				}
				return this._generated_field_39;
			}
		}
		
		protected TextView Generated_ViewElement_11
		{
			get
			{
				if ((this._generated_field_40 == null))
				{
					this._generated_field_40 = this.View.FindViewById<TextView>(Resource.Id.Generated_ViewElement_11);
				}
				return this._generated_field_40;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_41 == null))
				{
					this._generated_field_41 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_41;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_21 = new BindingObject(this.Generated_ViewElement_10);
			result.Add(generated_bindingObject_21);
			BindingExpression generated_bindingExpression_21 = new BindingExpression("Text", "Name");
			generated_bindingObject_21.AddExpression(generated_bindingExpression_21);
			BindingObject generated_bindingObject_22 = new BindingObject(this.Generated_ViewElement_11);
			result.Add(generated_bindingObject_22);
			BindingExpression generated_bindingExpression_22 = new BindingExpression("Text", "Description");
			generated_bindingObject_22.AddExpression(generated_bindingExpression_22);
			return result;
		}
	}
}
