//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace Storm.Generated
{
	
	
	public class Generated_ViewHolder_3 : Storm.Mvvm.BaseViewHolder
	{
		
		private TextView _generated_field_77;
		
		private ILocalizationService _generated_field_78;
		
		protected TextView Generated_ViewElement_11
		{
			get
			{
				if ((this._generated_field_77 == null))
				{
					this._generated_field_77 = this.View.FindViewById<TextView>(Resource.Id.Generated_ViewElement_11);
				}
				return this._generated_field_77;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_78 == null))
				{
					this._generated_field_78 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_78;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_55 = new BindingObject(this.Generated_ViewElement_11);
			result.Add(generated_bindingObject_55);
			BindingExpression generated_bindingExpression_61 = new BindingExpression("Text", "Name");
			generated_bindingObject_55.AddExpression(generated_bindingExpression_61);
			return result;
		}
	}
}
