//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class HomeActivity
	{
		
		private Storm.Mvvm.Components.BindableListView _generated_field_343;
		
		private Button _generated_field_344;
		
		private Button _generated_field_345;
		
		private ILocalizationService _generated_field_346;
		
		private Storm.Mvvm.DataTemplate _generated_field_347;
		
		private Storm.Mvvm.TemplateSelectors.SimpleTemplateSelector _generated_field_348;
		
		private Storm.Mvvm.Adapters.BindableAdapter _generated_field_349;
		
		protected Storm.Mvvm.Components.BindableListView ListView
		{
			get
			{
				if ((this._generated_field_343 == null))
				{
					this._generated_field_343 = this.FindViewById<Storm.Mvvm.Components.BindableListView>(Resource.Id.ListView);
				}
				return this._generated_field_343;
			}
		}
		
		protected Button Generated_ViewElement_82
		{
			get
			{
				if ((this._generated_field_344 == null))
				{
					this._generated_field_344 = this.FindViewById<Button>(Resource.Id.Generated_ViewElement_82);
				}
				return this._generated_field_344;
			}
		}
		
		protected Button Generated_ViewElement_83
		{
			get
			{
				if ((this._generated_field_345 == null))
				{
					this._generated_field_345 = this.FindViewById<Button>(Resource.Id.Generated_ViewElement_83);
				}
				return this._generated_field_345;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_346 == null))
				{
					this._generated_field_346 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_346;
			}
		}
		
		protected Storm.Mvvm.DataTemplate Generated_Resource_57
		{
			get
			{
				if ((this._generated_field_347 == null))
				{
					this._generated_field_347 = new Storm.Mvvm.DataTemplate();
					this._generated_field_347.ViewId = Resource.Layout.Home_DT_ListViewTemplate;
					this._generated_field_347.LayoutInflater = this.LayoutInflater;
					this._generated_field_347.ViewHolderType = typeof(Storm.Generated.Generated_ViewHolder_14);
				}
				return this._generated_field_347;
			}
		}
		
		protected Storm.Mvvm.TemplateSelectors.SimpleTemplateSelector Generated_Resource_58
		{
			get
			{
				if ((this._generated_field_348 == null))
				{
					this._generated_field_348 = new Storm.Mvvm.TemplateSelectors.SimpleTemplateSelector();
				}
				return this._generated_field_348;
			}
		}
		
		protected Storm.Mvvm.Adapters.BindableAdapter Generated_Resource_59
		{
			get
			{
				if ((this._generated_field_349 == null))
				{
					this._generated_field_349 = new Storm.Mvvm.Adapters.BindableAdapter();
				}
				return this._generated_field_349;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
			this.Generated_Resource_59.GetType().GetProperty("TemplateSelector", BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance).SetValue(this.Generated_Resource_59, this.Generated_Resource_58);
			this.Generated_Resource_58.GetType().GetProperty("Template", BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance).SetValue(this.Generated_Resource_58, this.Generated_Resource_57);
		}
		
		private void Generated_AssignResourceForView()
		{
			this.ListView.GetType().GetProperty("adapter", BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance).SetValue(this.ListView, this.Generated_Resource_59);
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_243 = new BindingObject(this.Generated_Resource_59);
			result.Add(generated_bindingObject_243);
			BindingExpression generated_bindingExpression_271 = new BindingExpression("Collection", "CollectionTodo");
			generated_bindingObject_243.AddExpression(generated_bindingExpression_271);
			BindingObject generated_bindingObject_244 = new BindingObject(this.ListView);
			result.Add(generated_bindingObject_244);
			BindingExpression generated_bindingExpression_272 = new BindingExpression("CurrentItem", "SelectedTodo");
			generated_bindingExpression_272.Mode = BindingMode.TwoWay;
			generated_bindingExpression_272.UpdateEvent = "CurrentItemChanged";
			generated_bindingObject_244.AddExpression(generated_bindingExpression_272);
			BindingObject generated_bindingObject_245 = new BindingObject(this.Generated_ViewElement_82);
			result.Add(generated_bindingObject_245);
			BindingExpression generated_bindingExpression_273 = new BindingExpression("Click", "ButtonAdd");
			generated_bindingObject_245.AddExpression(generated_bindingExpression_273);
			BindingObject generated_bindingObject_246 = new BindingObject(this.Generated_ViewElement_83);
			result.Add(generated_bindingObject_246);
			BindingExpression generated_bindingExpression_274 = new BindingExpression("Click", "ButtonEdit");
			generated_bindingObject_246.AddExpression(generated_bindingExpression_274);
			return result;
		}
	}
}
