//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class EditActivity
	{
		
		private EditText _generated_field_254;
		
		private EditText _generated_field_255;
		
		private Button _generated_field_256;
		
		private Button _generated_field_257;
		
		private Button _generated_field_258;
		
		private ILocalizationService _generated_field_259;
		
		protected EditText nameEdit
		{
			get
			{
				if ((this._generated_field_254 == null))
				{
					this._generated_field_254 = this.FindViewById<EditText>(Resource.Id.nameEdit);
				}
				return this._generated_field_254;
			}
		}
		
		protected EditText descEdit
		{
			get
			{
				if ((this._generated_field_255 == null))
				{
					this._generated_field_255 = this.FindViewById<EditText>(Resource.Id.descEdit);
				}
				return this._generated_field_255;
			}
		}
		
		protected Button Edit
		{
			get
			{
				if ((this._generated_field_256 == null))
				{
					this._generated_field_256 = this.FindViewById<Button>(Resource.Id.Edit);
				}
				return this._generated_field_256;
			}
		}
		
		protected Button Delete
		{
			get
			{
				if ((this._generated_field_257 == null))
				{
					this._generated_field_257 = this.FindViewById<Button>(Resource.Id.Delete);
				}
				return this._generated_field_257;
			}
		}
		
		protected Button back
		{
			get
			{
				if ((this._generated_field_258 == null))
				{
					this._generated_field_258 = this.FindViewById<Button>(Resource.Id.back);
				}
				return this._generated_field_258;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_259 == null))
				{
					this._generated_field_259 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_259;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_169 = new BindingObject(this.nameEdit);
			result.Add(generated_bindingObject_169);
			BindingExpression generated_bindingExpression_189 = new BindingExpression("hint", "Title");
			generated_bindingObject_169.AddExpression(generated_bindingExpression_189);
			BindingExpression generated_bindingExpression_190 = new BindingExpression("Text", "Title");
			generated_bindingExpression_190.Mode = BindingMode.TwoWay;
			generated_bindingExpression_190.UpdateEvent = "TextChanged";
			generated_bindingObject_169.AddExpression(generated_bindingExpression_190);
			BindingObject generated_bindingObject_170 = new BindingObject(this.descEdit);
			result.Add(generated_bindingObject_170);
			BindingExpression generated_bindingExpression_191 = new BindingExpression("hint", "Description");
			generated_bindingObject_170.AddExpression(generated_bindingExpression_191);
			BindingExpression generated_bindingExpression_192 = new BindingExpression("Text", "Description");
			generated_bindingExpression_192.Mode = BindingMode.TwoWay;
			generated_bindingExpression_192.UpdateEvent = "TextChanged";
			generated_bindingObject_170.AddExpression(generated_bindingExpression_192);
			BindingObject generated_bindingObject_171 = new BindingObject(this.Edit);
			result.Add(generated_bindingObject_171);
			BindingExpression generated_bindingExpression_193 = new BindingExpression("Click", "ButtonSaveEdit");
			generated_bindingObject_171.AddExpression(generated_bindingExpression_193);
			BindingObject generated_bindingObject_172 = new BindingObject(this.Delete);
			result.Add(generated_bindingObject_172);
			BindingExpression generated_bindingExpression_194 = new BindingExpression("Click", "ButtonDelete");
			generated_bindingObject_172.AddExpression(generated_bindingExpression_194);
			BindingObject generated_bindingObject_173 = new BindingObject(this.back);
			result.Add(generated_bindingObject_173);
			BindingExpression generated_bindingExpression_195 = new BindingExpression("Click", "ButtonBack");
			generated_bindingObject_173.AddExpression(generated_bindingExpression_195);
			return result;
		}
	}
}
