//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class LoginActivity
	{
		
		private EditText _generated_field_1014;
		
		private EditText _generated_field_1015;
		
		private CheckBox _generated_field_1016;
		
		private Button _generated_field_1017;
		
		private Button _generated_field_1018;
		
		private TextView _generated_field_1019;
		
		private ILocalizationService _generated_field_1020;
		
		protected EditText Generated_ViewElement_351
		{
			get
			{
				if ((this._generated_field_1014 == null))
				{
					this._generated_field_1014 = this.FindViewById<EditText>(Resource.Id.Generated_ViewElement_351);
				}
				return this._generated_field_1014;
			}
		}
		
		protected EditText Generated_ViewElement_352
		{
			get
			{
				if ((this._generated_field_1015 == null))
				{
					this._generated_field_1015 = this.FindViewById<EditText>(Resource.Id.Generated_ViewElement_352);
				}
				return this._generated_field_1015;
			}
		}
		
		protected CheckBox Generated_ViewElement_353
		{
			get
			{
				if ((this._generated_field_1016 == null))
				{
					this._generated_field_1016 = this.FindViewById<CheckBox>(Resource.Id.Generated_ViewElement_353);
				}
				return this._generated_field_1016;
			}
		}
		
		protected Button Generated_ViewElement_354
		{
			get
			{
				if ((this._generated_field_1017 == null))
				{
					this._generated_field_1017 = this.FindViewById<Button>(Resource.Id.Generated_ViewElement_354);
				}
				return this._generated_field_1017;
			}
		}
		
		protected Button Generated_ViewElement_355
		{
			get
			{
				if ((this._generated_field_1018 == null))
				{
					this._generated_field_1018 = this.FindViewById<Button>(Resource.Id.Generated_ViewElement_355);
				}
				return this._generated_field_1018;
			}
		}
		
		protected TextView Generated_ViewElement_356
		{
			get
			{
				if ((this._generated_field_1019 == null))
				{
					this._generated_field_1019 = this.FindViewById<TextView>(Resource.Id.Generated_ViewElement_356);
				}
				return this._generated_field_1019;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_1020 == null))
				{
					this._generated_field_1020 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_1020;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_741 = new BindingObject(this.Generated_ViewElement_351);
			result.Add(generated_bindingObject_741);
			BindingExpression generated_bindingExpression_819 = new BindingExpression("Text", "Id");
			generated_bindingExpression_819.Mode = BindingMode.TwoWay;
			generated_bindingExpression_819.UpdateEvent = "TextChanged";
			generated_bindingObject_741.AddExpression(generated_bindingExpression_819);
			BindingObject generated_bindingObject_742 = new BindingObject(this.Generated_ViewElement_352);
			result.Add(generated_bindingObject_742);
			BindingExpression generated_bindingExpression_820 = new BindingExpression("Text", "Pass");
			generated_bindingExpression_820.Mode = BindingMode.TwoWay;
			generated_bindingExpression_820.UpdateEvent = "TextChanged";
			generated_bindingObject_742.AddExpression(generated_bindingExpression_820);
			BindingObject generated_bindingObject_743 = new BindingObject(this.Generated_ViewElement_353);
			result.Add(generated_bindingObject_743);
			BindingExpression generated_bindingExpression_821 = new BindingExpression("Checked", "RememberChecked");
			generated_bindingExpression_821.Mode = BindingMode.TwoWay;
			generated_bindingExpression_821.UpdateEvent = "CheckedChange";
			generated_bindingObject_743.AddExpression(generated_bindingExpression_821);
			BindingObject generated_bindingObject_744 = new BindingObject(this.Generated_ViewElement_354);
			result.Add(generated_bindingObject_744);
			BindingExpression generated_bindingExpression_822 = new BindingExpression("Click", "ButtonLogin");
			generated_bindingObject_744.AddExpression(generated_bindingExpression_822);
			BindingObject generated_bindingObject_745 = new BindingObject(this.Generated_ViewElement_355);
			result.Add(generated_bindingObject_745);
			BindingExpression generated_bindingExpression_823 = new BindingExpression("Click", "ButtonSignUp");
			generated_bindingObject_745.AddExpression(generated_bindingExpression_823);
			BindingObject generated_bindingObject_746 = new BindingObject(this.Generated_ViewElement_356);
			result.Add(generated_bindingObject_746);
			BindingExpression generated_bindingExpression_824 = new BindingExpression("Text", "Error");
			generated_bindingObject_746.AddExpression(generated_bindingExpression_824);
			return result;
		}
	}
}
