//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class EditActivity
	{
		
		private EditText _generated_field_194;
		
		private EditText _generated_field_195;
		
		private Button _generated_field_196;
		
		private Button _generated_field_197;
		
		private Button _generated_field_198;
		
		private ILocalizationService _generated_field_199;
		
		protected EditText nameEdit
		{
			get
			{
				if ((this._generated_field_194 == null))
				{
					this._generated_field_194 = this.FindViewById<EditText>(Resource.Id.nameEdit);
				}
				return this._generated_field_194;
			}
		}
		
		protected EditText descEdit
		{
			get
			{
				if ((this._generated_field_195 == null))
				{
					this._generated_field_195 = this.FindViewById<EditText>(Resource.Id.descEdit);
				}
				return this._generated_field_195;
			}
		}
		
		protected Button Edit
		{
			get
			{
				if ((this._generated_field_196 == null))
				{
					this._generated_field_196 = this.FindViewById<Button>(Resource.Id.Edit);
				}
				return this._generated_field_196;
			}
		}
		
		protected Button Delete
		{
			get
			{
				if ((this._generated_field_197 == null))
				{
					this._generated_field_197 = this.FindViewById<Button>(Resource.Id.Delete);
				}
				return this._generated_field_197;
			}
		}
		
		protected Button back
		{
			get
			{
				if ((this._generated_field_198 == null))
				{
					this._generated_field_198 = this.FindViewById<Button>(Resource.Id.back);
				}
				return this._generated_field_198;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_199 == null))
				{
					this._generated_field_199 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_199;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_139 = new BindingObject(this.nameEdit);
			result.Add(generated_bindingObject_139);
			BindingExpression generated_bindingExpression_153 = new BindingExpression("hint", "Title");
			generated_bindingObject_139.AddExpression(generated_bindingExpression_153);
			BindingExpression generated_bindingExpression_154 = new BindingExpression("Text", "Title");
			generated_bindingExpression_154.Mode = BindingMode.TwoWay;
			generated_bindingExpression_154.UpdateEvent = "TextChanged";
			generated_bindingObject_139.AddExpression(generated_bindingExpression_154);
			BindingObject generated_bindingObject_140 = new BindingObject(this.descEdit);
			result.Add(generated_bindingObject_140);
			BindingExpression generated_bindingExpression_155 = new BindingExpression("hint", "Description");
			generated_bindingObject_140.AddExpression(generated_bindingExpression_155);
			BindingExpression generated_bindingExpression_156 = new BindingExpression("Text", "Description");
			generated_bindingExpression_156.Mode = BindingMode.TwoWay;
			generated_bindingExpression_156.UpdateEvent = "TextChanged";
			generated_bindingObject_140.AddExpression(generated_bindingExpression_156);
			BindingObject generated_bindingObject_141 = new BindingObject(this.Edit);
			result.Add(generated_bindingObject_141);
			BindingExpression generated_bindingExpression_157 = new BindingExpression("Click", "ButtonSaveEdit");
			generated_bindingObject_141.AddExpression(generated_bindingExpression_157);
			BindingObject generated_bindingObject_142 = new BindingObject(this.Delete);
			result.Add(generated_bindingObject_142);
			BindingExpression generated_bindingExpression_158 = new BindingExpression("Click", "ButtonDelete");
			generated_bindingObject_142.AddExpression(generated_bindingExpression_158);
			BindingObject generated_bindingObject_143 = new BindingObject(this.back);
			result.Add(generated_bindingObject_143);
			BindingExpression generated_bindingExpression_159 = new BindingExpression("Click", "ButtonBack");
			generated_bindingObject_143.AddExpression(generated_bindingExpression_159);
			return result;
		}
	}
}
