//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class LoginActivity
	{
		
		private EditText _generated_field_336;
		
		private EditText _generated_field_337;
		
		private Button _generated_field_338;
		
		private Button _generated_field_339;
		
		private ILocalizationService _generated_field_340;
		
		protected EditText Generated_ViewElement_78
		{
			get
			{
				if ((this._generated_field_336 == null))
				{
					this._generated_field_336 = this.FindViewById<EditText>(Resource.Id.Generated_ViewElement_78);
				}
				return this._generated_field_336;
			}
		}
		
		protected EditText Generated_ViewElement_79
		{
			get
			{
				if ((this._generated_field_337 == null))
				{
					this._generated_field_337 = this.FindViewById<EditText>(Resource.Id.Generated_ViewElement_79);
				}
				return this._generated_field_337;
			}
		}
		
		protected Button Generated_ViewElement_80
		{
			get
			{
				if ((this._generated_field_338 == null))
				{
					this._generated_field_338 = this.FindViewById<Button>(Resource.Id.Generated_ViewElement_80);
				}
				return this._generated_field_338;
			}
		}
		
		protected Button Generated_ViewElement_81
		{
			get
			{
				if ((this._generated_field_339 == null))
				{
					this._generated_field_339 = this.FindViewById<Button>(Resource.Id.Generated_ViewElement_81);
				}
				return this._generated_field_339;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_340 == null))
				{
					this._generated_field_340 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_340;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_238 = new BindingObject(this.Generated_ViewElement_78);
			result.Add(generated_bindingObject_238);
			BindingExpression generated_bindingExpression_266 = new BindingExpression("Text", "Id");
			generated_bindingExpression_266.Mode = BindingMode.TwoWay;
			generated_bindingExpression_266.UpdateEvent = "TextChanged";
			generated_bindingObject_238.AddExpression(generated_bindingExpression_266);
			BindingObject generated_bindingObject_239 = new BindingObject(this.Generated_ViewElement_79);
			result.Add(generated_bindingObject_239);
			BindingExpression generated_bindingExpression_267 = new BindingExpression("Text", "Pass");
			generated_bindingExpression_267.Mode = BindingMode.TwoWay;
			generated_bindingExpression_267.UpdateEvent = "TextChanged";
			generated_bindingObject_239.AddExpression(generated_bindingExpression_267);
			BindingObject generated_bindingObject_240 = new BindingObject(this.Generated_ViewElement_80);
			result.Add(generated_bindingObject_240);
			BindingExpression generated_bindingExpression_268 = new BindingExpression("Click", "ButtonLogin");
			generated_bindingObject_240.AddExpression(generated_bindingExpression_268);
			BindingObject generated_bindingObject_241 = new BindingObject(this.Generated_ViewElement_81);
			result.Add(generated_bindingObject_241);
			BindingExpression generated_bindingExpression_269 = new BindingExpression("Click", "ButtonSignUp");
			generated_bindingObject_241.AddExpression(generated_bindingExpression_269);
			return result;
		}
	}
}
