//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class DisplayActivity
	{
		
		private ListView _generated_field_24;
		
		private RelativeLayout _generated_field_25;
		
		private Button _generated_field_26;
		
		private ILocalizationService _generated_field_27;
		
		protected ListView listView
		{
			get
			{
				if ((this._generated_field_24 == null))
				{
					this._generated_field_24 = this.FindViewById<ListView>(Resource.Id.listView);
				}
				return this._generated_field_24;
			}
		}
		
		protected RelativeLayout InnerRelativeLayout
		{
			get
			{
				if ((this._generated_field_25 == null))
				{
					this._generated_field_25 = this.FindViewById<RelativeLayout>(Resource.Id.InnerRelativeLayout);
				}
				return this._generated_field_25;
			}
		}
		
		protected Button add
		{
			get
			{
				if ((this._generated_field_26 == null))
				{
					this._generated_field_26 = this.FindViewById<Button>(Resource.Id.add);
				}
				return this._generated_field_26;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_27 == null))
				{
					this._generated_field_27 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_27;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_3 = new BindingObject(this.add);
			result.Add(generated_bindingObject_3);
			BindingExpression generated_bindingExpression_3 = new BindingExpression("Click", "ButtonAdd");
			generated_bindingObject_3.AddExpression(generated_bindingExpression_3);
			return result;
		}
	}
}
