//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class HomeActivity
	{
		
		private Storm.Mvvm.Components.BindableListView _generated_field_21;
		
		private Button _generated_field_22;
		
		private Button _generated_field_23;
		
		private ILocalizationService _generated_field_24;
		
		private Storm.Mvvm.DataTemplate _generated_field_25;
		
		private Storm.Mvvm.TemplateSelectors.SimpleTemplateSelector _generated_field_26;
		
		private Storm.Mvvm.Adapters.BindableAdapter _generated_field_27;
		
		protected Storm.Mvvm.Components.BindableListView ListView
		{
			get
			{
				if ((this._generated_field_21 == null))
				{
					this._generated_field_21 = this.FindViewById<Storm.Mvvm.Components.BindableListView>(Resource.Id.ListView);
				}
				return this._generated_field_21;
			}
		}
		
		protected Button Generated_ViewElement_3
		{
			get
			{
				if ((this._generated_field_22 == null))
				{
					this._generated_field_22 = this.FindViewById<Button>(Resource.Id.Generated_ViewElement_3);
				}
				return this._generated_field_22;
			}
		}
		
		protected Button Generated_ViewElement_4
		{
			get
			{
				if ((this._generated_field_23 == null))
				{
					this._generated_field_23 = this.FindViewById<Button>(Resource.Id.Generated_ViewElement_4);
				}
				return this._generated_field_23;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_24 == null))
				{
					this._generated_field_24 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_24;
			}
		}
		
		protected Storm.Mvvm.DataTemplate Generated_Resource_5
		{
			get
			{
				if ((this._generated_field_25 == null))
				{
					this._generated_field_25 = new Storm.Mvvm.DataTemplate();
					this._generated_field_25.ViewId = Resource.Layout.Home_DT_ListViewTemplate;
					this._generated_field_25.LayoutInflater = this.LayoutInflater;
					this._generated_field_25.ViewHolderType = typeof(Storm.Generated.Generated_ViewHolder_1);
				}
				return this._generated_field_25;
			}
		}
		
		protected Storm.Mvvm.TemplateSelectors.SimpleTemplateSelector Generated_Resource_6
		{
			get
			{
				if ((this._generated_field_26 == null))
				{
					this._generated_field_26 = new Storm.Mvvm.TemplateSelectors.SimpleTemplateSelector();
				}
				return this._generated_field_26;
			}
		}
		
		protected Storm.Mvvm.Adapters.BindableAdapter Generated_Resource_7
		{
			get
			{
				if ((this._generated_field_27 == null))
				{
					this._generated_field_27 = new Storm.Mvvm.Adapters.BindableAdapter();
				}
				return this._generated_field_27;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
			this.Generated_Resource_7.GetType().GetProperty("TemplateSelector", BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance).SetValue(this.Generated_Resource_7, this.Generated_Resource_6);
			this.Generated_Resource_6.GetType().GetProperty("Template", BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance).SetValue(this.Generated_Resource_6, this.Generated_Resource_5);
		}
		
		private void Generated_AssignResourceForView()
		{
			this.ListView.GetType().GetProperty("adapter", BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance).SetValue(this.ListView, this.Generated_Resource_7);
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_14 = new BindingObject(this.Generated_Resource_7);
			result.Add(generated_bindingObject_14);
			BindingExpression generated_bindingExpression_16 = new BindingExpression("Collection", "CollectionTodo");
			generated_bindingObject_14.AddExpression(generated_bindingExpression_16);
			BindingObject generated_bindingObject_15 = new BindingObject(this.ListView);
			result.Add(generated_bindingObject_15);
			BindingExpression generated_bindingExpression_17 = new BindingExpression("CurrentItem", "SelectedTodo");
			generated_bindingExpression_17.Mode = BindingMode.TwoWay;
			generated_bindingExpression_17.UpdateEvent = "CurrentItemChanged";
			generated_bindingObject_15.AddExpression(generated_bindingExpression_17);
			BindingObject generated_bindingObject_16 = new BindingObject(this.Generated_ViewElement_3);
			result.Add(generated_bindingObject_16);
			BindingExpression generated_bindingExpression_18 = new BindingExpression("Click", "ButtonAdd");
			generated_bindingObject_16.AddExpression(generated_bindingExpression_18);
			BindingObject generated_bindingObject_17 = new BindingObject(this.Generated_ViewElement_4);
			result.Add(generated_bindingObject_17);
			BindingExpression generated_bindingExpression_19 = new BindingExpression("Click", "ButtonEdit");
			generated_bindingObject_17.AddExpression(generated_bindingExpression_19);
			return result;
		}
	}
}
