//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class AddActivity
	{
		
		private EditText _generated_field_350;
		
		private EditText _generated_field_351;
		
		private Button _generated_field_352;
		
		private ILocalizationService _generated_field_353;
		
		protected EditText name
		{
			get
			{
				if ((this._generated_field_350 == null))
				{
					this._generated_field_350 = this.FindViewById<EditText>(Resource.Id.name);
				}
				return this._generated_field_350;
			}
		}
		
		protected EditText descitption
		{
			get
			{
				if ((this._generated_field_351 == null))
				{
					this._generated_field_351 = this.FindViewById<EditText>(Resource.Id.descitption);
				}
				return this._generated_field_351;
			}
		}
		
		protected Button save
		{
			get
			{
				if ((this._generated_field_352 == null))
				{
					this._generated_field_352 = this.FindViewById<Button>(Resource.Id.save);
				}
				return this._generated_field_352;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_353 == null))
				{
					this._generated_field_353 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_353;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_247 = new BindingObject(this.name);
			result.Add(generated_bindingObject_247);
			BindingExpression generated_bindingExpression_275 = new BindingExpression("Text", "Title");
			generated_bindingExpression_275.Mode = BindingMode.TwoWay;
			generated_bindingExpression_275.UpdateEvent = "TextChanged";
			generated_bindingObject_247.AddExpression(generated_bindingExpression_275);
			BindingObject generated_bindingObject_248 = new BindingObject(this.descitption);
			result.Add(generated_bindingObject_248);
			BindingExpression generated_bindingExpression_276 = new BindingExpression("Text", "Description");
			generated_bindingExpression_276.Mode = BindingMode.TwoWay;
			generated_bindingExpression_276.UpdateEvent = "TextChanged";
			generated_bindingObject_248.AddExpression(generated_bindingExpression_276);
			BindingObject generated_bindingObject_249 = new BindingObject(this.save);
			result.Add(generated_bindingObject_249);
			BindingExpression generated_bindingExpression_277 = new BindingExpression("Click", "ButtonSave");
			generated_bindingObject_249.AddExpression(generated_bindingExpression_277);
			return result;
		}
	}
}
