//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class AddActivity
	{
		
		private EditText _generated_field_28;
		
		private EditText _generated_field_29;
		
		private Button _generated_field_30;
		
		private ILocalizationService _generated_field_31;
		
		protected EditText name
		{
			get
			{
				if ((this._generated_field_28 == null))
				{
					this._generated_field_28 = this.FindViewById<EditText>(Resource.Id.name);
				}
				return this._generated_field_28;
			}
		}
		
		protected EditText descitption
		{
			get
			{
				if ((this._generated_field_29 == null))
				{
					this._generated_field_29 = this.FindViewById<EditText>(Resource.Id.descitption);
				}
				return this._generated_field_29;
			}
		}
		
		protected Button save
		{
			get
			{
				if ((this._generated_field_30 == null))
				{
					this._generated_field_30 = this.FindViewById<Button>(Resource.Id.save);
				}
				return this._generated_field_30;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_31 == null))
				{
					this._generated_field_31 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_31;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_18 = new BindingObject(this.name);
			result.Add(generated_bindingObject_18);
			BindingExpression generated_bindingExpression_20 = new BindingExpression("Text", "Title");
			generated_bindingExpression_20.Mode = BindingMode.TwoWay;
			generated_bindingExpression_20.UpdateEvent = "TextChanged";
			generated_bindingObject_18.AddExpression(generated_bindingExpression_20);
			BindingObject generated_bindingObject_19 = new BindingObject(this.descitption);
			result.Add(generated_bindingObject_19);
			BindingExpression generated_bindingExpression_21 = new BindingExpression("Text", "Description");
			generated_bindingExpression_21.Mode = BindingMode.TwoWay;
			generated_bindingExpression_21.UpdateEvent = "TextChanged";
			generated_bindingObject_19.AddExpression(generated_bindingExpression_21);
			BindingObject generated_bindingObject_20 = new BindingObject(this.save);
			result.Add(generated_bindingObject_20);
			BindingExpression generated_bindingExpression_22 = new BindingExpression("Click", "ButtonSave");
			generated_bindingObject_20.AddExpression(generated_bindingExpression_22);
			return result;
		}
	}
}
