//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class LoginActivity
	{
		
		private EditText _generated_field_175;
		
		private EditText _generated_field_176;
		
		private CheckBox _generated_field_177;
		
		private Button _generated_field_178;
		
		private Button _generated_field_179;
		
		private ILocalizationService _generated_field_180;
		
		protected EditText Generated_ViewElement_56
		{
			get
			{
				if ((this._generated_field_175 == null))
				{
					this._generated_field_175 = this.FindViewById<EditText>(Resource.Id.Generated_ViewElement_56);
				}
				return this._generated_field_175;
			}
		}
		
		protected EditText Generated_ViewElement_57
		{
			get
			{
				if ((this._generated_field_176 == null))
				{
					this._generated_field_176 = this.FindViewById<EditText>(Resource.Id.Generated_ViewElement_57);
				}
				return this._generated_field_176;
			}
		}
		
		protected CheckBox Generated_ViewElement_58
		{
			get
			{
				if ((this._generated_field_177 == null))
				{
					this._generated_field_177 = this.FindViewById<CheckBox>(Resource.Id.Generated_ViewElement_58);
				}
				return this._generated_field_177;
			}
		}
		
		protected Button Generated_ViewElement_59
		{
			get
			{
				if ((this._generated_field_178 == null))
				{
					this._generated_field_178 = this.FindViewById<Button>(Resource.Id.Generated_ViewElement_59);
				}
				return this._generated_field_178;
			}
		}
		
		protected Button Generated_ViewElement_60
		{
			get
			{
				if ((this._generated_field_179 == null))
				{
					this._generated_field_179 = this.FindViewById<Button>(Resource.Id.Generated_ViewElement_60);
				}
				return this._generated_field_179;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_180 == null))
				{
					this._generated_field_180 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_180;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_126 = new BindingObject(this.Generated_ViewElement_56);
			result.Add(generated_bindingObject_126);
			BindingExpression generated_bindingExpression_140 = new BindingExpression("Text", "Id");
			generated_bindingExpression_140.Mode = BindingMode.TwoWay;
			generated_bindingExpression_140.UpdateEvent = "TextChanged";
			generated_bindingObject_126.AddExpression(generated_bindingExpression_140);
			BindingObject generated_bindingObject_127 = new BindingObject(this.Generated_ViewElement_57);
			result.Add(generated_bindingObject_127);
			BindingExpression generated_bindingExpression_141 = new BindingExpression("Text", "Pass");
			generated_bindingExpression_141.Mode = BindingMode.TwoWay;
			generated_bindingExpression_141.UpdateEvent = "TextChanged";
			generated_bindingObject_127.AddExpression(generated_bindingExpression_141);
			BindingObject generated_bindingObject_128 = new BindingObject(this.Generated_ViewElement_58);
			result.Add(generated_bindingObject_128);
			BindingExpression generated_bindingExpression_142 = new BindingExpression("Checked", "RememberChecked");
			generated_bindingExpression_142.Mode = BindingMode.TwoWay;
			generated_bindingExpression_142.UpdateEvent = "CheckedChange";
			generated_bindingObject_128.AddExpression(generated_bindingExpression_142);
			BindingObject generated_bindingObject_129 = new BindingObject(this.Generated_ViewElement_59);
			result.Add(generated_bindingObject_129);
			BindingExpression generated_bindingExpression_143 = new BindingExpression("Click", "ButtonLogin");
			generated_bindingObject_129.AddExpression(generated_bindingExpression_143);
			BindingObject generated_bindingObject_130 = new BindingObject(this.Generated_ViewElement_60);
			result.Add(generated_bindingObject_130);
			BindingExpression generated_bindingExpression_144 = new BindingExpression("Click", "ButtonSignUp");
			generated_bindingObject_130.AddExpression(generated_bindingExpression_144);
			return result;
		}
	}
}
