//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class EditActivity
	{
		
		private EditText _generated_field_1034;
		
		private EditText _generated_field_1035;
		
		private Button _generated_field_1036;
		
		private Button _generated_field_1037;
		
		private Button _generated_field_1038;
		
		private ILocalizationService _generated_field_1039;
		
		protected EditText nameEdit
		{
			get
			{
				if ((this._generated_field_1034 == null))
				{
					this._generated_field_1034 = this.FindViewById<EditText>(Resource.Id.nameEdit);
				}
				return this._generated_field_1034;
			}
		}
		
		protected EditText descEdit
		{
			get
			{
				if ((this._generated_field_1035 == null))
				{
					this._generated_field_1035 = this.FindViewById<EditText>(Resource.Id.descEdit);
				}
				return this._generated_field_1035;
			}
		}
		
		protected Button Edit
		{
			get
			{
				if ((this._generated_field_1036 == null))
				{
					this._generated_field_1036 = this.FindViewById<Button>(Resource.Id.Edit);
				}
				return this._generated_field_1036;
			}
		}
		
		protected Button Delete
		{
			get
			{
				if ((this._generated_field_1037 == null))
				{
					this._generated_field_1037 = this.FindViewById<Button>(Resource.Id.Delete);
				}
				return this._generated_field_1037;
			}
		}
		
		protected Button back
		{
			get
			{
				if ((this._generated_field_1038 == null))
				{
					this._generated_field_1038 = this.FindViewById<Button>(Resource.Id.back);
				}
				return this._generated_field_1038;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_1039 == null))
				{
					this._generated_field_1039 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_1039;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_755 = new BindingObject(this.nameEdit);
			result.Add(generated_bindingObject_755);
			BindingExpression generated_bindingExpression_833 = new BindingExpression("hint", "Title");
			generated_bindingObject_755.AddExpression(generated_bindingExpression_833);
			BindingExpression generated_bindingExpression_834 = new BindingExpression("Text", "Title");
			generated_bindingExpression_834.Mode = BindingMode.TwoWay;
			generated_bindingExpression_834.UpdateEvent = "TextChanged";
			generated_bindingObject_755.AddExpression(generated_bindingExpression_834);
			BindingObject generated_bindingObject_756 = new BindingObject(this.descEdit);
			result.Add(generated_bindingObject_756);
			BindingExpression generated_bindingExpression_835 = new BindingExpression("hint", "Description");
			generated_bindingObject_756.AddExpression(generated_bindingExpression_835);
			BindingExpression generated_bindingExpression_836 = new BindingExpression("Text", "Description");
			generated_bindingExpression_836.Mode = BindingMode.TwoWay;
			generated_bindingExpression_836.UpdateEvent = "TextChanged";
			generated_bindingObject_756.AddExpression(generated_bindingExpression_836);
			BindingObject generated_bindingObject_757 = new BindingObject(this.Edit);
			result.Add(generated_bindingObject_757);
			BindingExpression generated_bindingExpression_837 = new BindingExpression("Click", "ButtonSaveEdit");
			generated_bindingObject_757.AddExpression(generated_bindingExpression_837);
			BindingObject generated_bindingObject_758 = new BindingObject(this.Delete);
			result.Add(generated_bindingObject_758);
			BindingExpression generated_bindingExpression_838 = new BindingExpression("Click", "ButtonDelete");
			generated_bindingObject_758.AddExpression(generated_bindingExpression_838);
			BindingObject generated_bindingObject_759 = new BindingObject(this.back);
			result.Add(generated_bindingObject_759);
			BindingExpression generated_bindingExpression_839 = new BindingExpression("Click", "ButtonBack");
			generated_bindingObject_759.AddExpression(generated_bindingExpression_839);
			return result;
		}
	}
}
