//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class AddActivity
	{
		
		private EditText _generated_field_28;
		
		private EditText _generated_field_29;
		
		private Button _generated_field_30;
		
		private ILocalizationService _generated_field_31;
		
		protected EditText name
		{
			get
			{
				if ((this._generated_field_28 == null))
				{
					this._generated_field_28 = this.FindViewById<EditText>(Resource.Id.name);
				}
				return this._generated_field_28;
			}
		}
		
		protected EditText descitption
		{
			get
			{
				if ((this._generated_field_29 == null))
				{
					this._generated_field_29 = this.FindViewById<EditText>(Resource.Id.descitption);
				}
				return this._generated_field_29;
			}
		}
		
		protected Button save
		{
			get
			{
				if ((this._generated_field_30 == null))
				{
					this._generated_field_30 = this.FindViewById<Button>(Resource.Id.save);
				}
				return this._generated_field_30;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_31 == null))
				{
					this._generated_field_31 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_31;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			return result;
		}
	}
}
