//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class DisplayActivity
	{
		
		private EditText _generated_field_31;
		
		private EditText _generated_field_32;
		
		private Button _generated_field_33;
		
		private Button _generated_field_34;
		
		private ILocalizationService _generated_field_35;
		
		protected EditText nameEdit
		{
			get
			{
				if ((this._generated_field_31 == null))
				{
					this._generated_field_31 = this.FindViewById<EditText>(Resource.Id.nameEdit);
				}
				return this._generated_field_31;
			}
		}
		
		protected EditText descEdit
		{
			get
			{
				if ((this._generated_field_32 == null))
				{
					this._generated_field_32 = this.FindViewById<EditText>(Resource.Id.descEdit);
				}
				return this._generated_field_32;
			}
		}
		
		protected Button Edit
		{
			get
			{
				if ((this._generated_field_33 == null))
				{
					this._generated_field_33 = this.FindViewById<Button>(Resource.Id.Edit);
				}
				return this._generated_field_33;
			}
		}
		
		protected Button back
		{
			get
			{
				if ((this._generated_field_34 == null))
				{
					this._generated_field_34 = this.FindViewById<Button>(Resource.Id.back);
				}
				return this._generated_field_34;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_35 == null))
				{
					this._generated_field_35 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_35;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_20 = new BindingObject(this.nameEdit);
			result.Add(generated_bindingObject_20);
			BindingExpression generated_bindingExpression_22 = new BindingExpression("hint", "Title");
			generated_bindingObject_20.AddExpression(generated_bindingExpression_22);
			BindingExpression generated_bindingExpression_23 = new BindingExpression("Text", "Title");
			generated_bindingExpression_23.Mode = BindingMode.TwoWay;
			generated_bindingExpression_23.UpdateEvent = "TextChanged";
			generated_bindingObject_20.AddExpression(generated_bindingExpression_23);
			BindingObject generated_bindingObject_21 = new BindingObject(this.descEdit);
			result.Add(generated_bindingObject_21);
			BindingExpression generated_bindingExpression_24 = new BindingExpression("hint", "Description");
			generated_bindingObject_21.AddExpression(generated_bindingExpression_24);
			BindingExpression generated_bindingExpression_25 = new BindingExpression("Text", "Description");
			generated_bindingExpression_25.Mode = BindingMode.TwoWay;
			generated_bindingExpression_25.UpdateEvent = "TextChanged";
			generated_bindingObject_21.AddExpression(generated_bindingExpression_25);
			BindingObject generated_bindingObject_22 = new BindingObject(this.Edit);
			result.Add(generated_bindingObject_22);
			BindingExpression generated_bindingExpression_26 = new BindingExpression("Click", "ButtonSaveEdit");
			generated_bindingObject_22.AddExpression(generated_bindingExpression_26);
			BindingObject generated_bindingObject_23 = new BindingObject(this.back);
			result.Add(generated_bindingObject_23);
			BindingExpression generated_bindingExpression_27 = new BindingExpression("Click", "ButtonBack");
			generated_bindingObject_23.AddExpression(generated_bindingExpression_27);
			return result;
		}
	}
}
