//------------------------------------------------------------------------------
// This file was generated by binding preprocessing system for Android
//------------------------------------------------------------------------------

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Storm.Generated;
using Storm.Mvvm;
using Storm.Mvvm.Bindings;
using Storm.Mvvm.Components;
using Storm.Mvvm.Inject;
using Storm.Mvvm.Services;
using Storm.Mvvm.TemplateSelectors;
using System;
using System.Collections.Generic;
using System.Reflection;
using TodoList;


namespace TodoList.Activities
{
	
	
	public partial class SignActivity
	{
		
		private EditText _generated_field_237;
		
		private EditText _generated_field_238;
		
		private Button _generated_field_239;
		
		private ILocalizationService _generated_field_240;
		
		protected EditText id
		{
			get
			{
				if ((this._generated_field_237 == null))
				{
					this._generated_field_237 = this.FindViewById<EditText>(Resource.Id.id);
				}
				return this._generated_field_237;
			}
		}
		
		protected EditText pwd
		{
			get
			{
				if ((this._generated_field_238 == null))
				{
					this._generated_field_238 = this.FindViewById<EditText>(Resource.Id.pwd);
				}
				return this._generated_field_238;
			}
		}
		
		protected Button signup
		{
			get
			{
				if ((this._generated_field_239 == null))
				{
					this._generated_field_239 = this.FindViewById<Button>(Resource.Id.signup);
				}
				return this._generated_field_239;
			}
		}
		
		protected ILocalizationService Generated_LocalizationService
		{
			get
			{
				if ((this._generated_field_240 == null))
				{
					this._generated_field_240 = DependencyService.Container.Resolve<ILocalizationService>();
				}
				return this._generated_field_240;
			}
		}
		
		private void Generated_AssignTranslation()
		{
		}
		
		private void Generated_AssignResourceForResource()
		{
		}
		
		private void Generated_AssignResourceForView()
		{
		}
		
		protected override List<BindingObject> GetBindingPaths()
		{
			this.Generated_AssignTranslation();
			this.Generated_AssignResourceForResource();
			this.Generated_AssignResourceForView();
			List<BindingObject> result = new List<BindingObject>();
			BindingObject generated_bindingObject_158 = new BindingObject(this.id);
			result.Add(generated_bindingObject_158);
			BindingExpression generated_bindingExpression_178 = new BindingExpression("Text", "Id");
			generated_bindingExpression_178.Mode = BindingMode.TwoWay;
			generated_bindingExpression_178.UpdateEvent = "TextChanged";
			generated_bindingObject_158.AddExpression(generated_bindingExpression_178);
			BindingObject generated_bindingObject_159 = new BindingObject(this.pwd);
			result.Add(generated_bindingObject_159);
			BindingExpression generated_bindingExpression_179 = new BindingExpression("Text", "Pass");
			generated_bindingExpression_179.Mode = BindingMode.TwoWay;
			generated_bindingExpression_179.UpdateEvent = "TextChanged";
			generated_bindingObject_159.AddExpression(generated_bindingExpression_179);
			BindingObject generated_bindingObject_160 = new BindingObject(this.signup);
			result.Add(generated_bindingObject_160);
			BindingExpression generated_bindingExpression_180 = new BindingExpression("Click", "ButtonSaveNew");
			generated_bindingObject_160.AddExpression(generated_bindingExpression_180);
			return result;
		}
	}
}
